In [1]:
import pandas as pd

In [25]:
import pandas as pd

df = pd.read_excel('data_set/sample_pivot.xlsx', parse_dates=['Date'])

print(df.head())

        Date Region                 Type  Units  Sales
0 2020-07-11   East  Children's Clothing   18.0    306
1 2020-09-23  North  Children's Clothing   14.0    448
2 2020-04-02  South     Women's Clothing   17.0    425
3 2020-02-28   East  Children's Clothing   26.0    832
4 2020-03-19   West     Women's Clothing    3.0     33

In [8]:
pivot = pd.pivot_table(df, index = ['Region', 'Type'], values = 'Sales', aggfunc = 'sum')

print(pivot)

                            Sales
Region Type
East   Children's Clothing  45849
       Men's Clothing       51685
       Women's Clothing     70229
North  Children's Clothing  37306
       Men's Clothing       39975
       Women's Clothing     61419
South  Children's Clothing  18570
       Men's Clothing       18542
       Women's Clothing     22203
West   Children's Clothing  20182
       Men's Clothing       19077
       Women's Clothing     22217

In [9]:
pivot.style.format({'Sales':'${0:,.0f}'})

In [ ]:
# Float with 2 decimal places: {:.2f}
# Pad numbers with zeroes: {:0>2d}
# Percent with 2 decimal places: {:.2%}

In [10]:
def highlight_fifty(val):
    color = 'red' if val > 50000 else 'black'
    return 'color: %s' % color

In [11]:
pivot_highlight = pivot.style.applymap(highlight_fifty)
pivot_highlight

/var/folders/f7/m8hfzm0j30l8vf635dzs58lc0000gn/T/ipykernel_10133/2659347415.py:1: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  pivot_highlight = pivot.style.applymap(highlight_fifty)

In [12]:
pivot_highlight = pivot.style.applymap(highlight_fifty).format({'Sales':'${0:,.0f}'})
pivot_highlight

/var/folders/f7/m8hfzm0j30l8vf635dzs58lc0000gn/T/ipykernel_10133/2708080837.py:1: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  pivot_highlight = pivot.style.applymap(highlight_fifty).format({'Sales':'${0:,.0f}'})

In [13]:
pivot_highlight = pivot.style.format({'Sales':'${0:,.0f}'})\
   .highlight_max(color='green')\
   .highlight_min(color='red')
pivot_highlight

In [14]:
pivot.style.format({'Sales':'${0:,.0f}'}) \
   .highlight_max(color='green') \
   .highlight_min(color='red')

In [17]:
pivot.style.background_gradient(cmap='RdYlGn')

In [16]:
from matplotlib import colormaps
list(colormaps)

['magma',
 'inferno',
 'plasma',
 'viridis',
 'cividis',
 'twilight',
 'twilight_shifted',
 'turbo',
 'berlin',
 'managua',
 'vanimo',
 'Blues',
 'BrBG',
 'BuGn',
 'BuPu',
 'CMRmap',
 'GnBu',
 'Greens',
 'Greys',
 'OrRd',
 'Oranges',
 'PRGn',
 'PiYG',
 'PuBu',
 'PuBuGn',
 'PuOr',
 'PuRd',
 'Purples',
 'RdBu',
 'RdGy',
 'RdPu',
 'RdYlBu',
 'RdYlGn',
 'Reds',
 'Spectral',
 'Wistia',
 'YlGn',
 'YlGnBu',
 'YlOrBr',
 'YlOrRd',
 'afmhot',
 'autumn',
 'binary',
 'bone',
 'brg',
 'bwr',
 'cool',
 'coolwarm',
 'copper',
 'cubehelix',
 'flag',
 'gist_earth',
 'gist_gray',
 'gist_heat',
 'gist_ncar',
 'gist_rainbow',
 'gist_stern',
 'gist_yarg',
 'gnuplot',
 'gnuplot2',
 'gray',
 'hot',
 'hsv',
 'jet',
 'nipy_spectral',
 'ocean',
 'pink',
 'prism',
 'rainbow',
 'seismic',
 'spring',
 'summer',
 'terrain',
 'winter',
 'Accent',
 'Dark2',
 'Paired',
 'Pastel1',
 'Pastel2',
 'Set1',
 'Set2',
 'Set3',
 'tab10',
 'tab20',
 'tab20b',
 'tab20c',
 'grey',
 'gist_grey',
 'gist_yerg',
 'Grays',
 'magma_r',
 'inferno_r',
 'plasma_r',
 'viridis_r',
 'cividis_r',
 'twilight_r',
 'twilight_shifted_r',
 'turbo_r',
 'berlin_r',
 'managua_r',
 'vanimo_r',
 'Blues_r',
 'BrBG_r',
 'BuGn_r',
 'BuPu_r',
 'CMRmap_r',
 'GnBu_r',
 'Greens_r',
 'Greys_r',
 'OrRd_r',
 'Oranges_r',
 'PRGn_r',
 'PiYG_r',
 'PuBu_r',
 'PuBuGn_r',
 'PuOr_r',
 'PuRd_r',
 'Purples_r',
 'RdBu_r',
 'RdGy_r',
 'RdPu_r',
 'RdYlBu_r',
 'RdYlGn_r',
 'Reds_r',
 'Spectral_r',
 'Wistia_r',
 'YlGn_r',
 'YlGnBu_r',
 'YlOrBr_r',
 'YlOrRd_r',
 'afmhot_r',
 'autumn_r',
 'binary_r',
 'bone_r',
 'brg_r',
 'bwr_r',
 'cool_r',
 'coolwarm_r',
 'copper_r',
 'cubehelix_r',
 'flag_r',
 'gist_earth_r',
 'gist_gray_r',
 'gist_heat_r',
 'gist_ncar_r',
 'gist_rainbow_r',
 'gist_stern_r',
 'gist_yarg_r',
 'gnuplot_r',
 'gnuplot2_r',
 'gray_r',
 'hot_r',
 'hsv_r',
 'jet_r',
 'nipy_spectral_r',
 'ocean_r',
 'pink_r',
 'prism_r',
 'rainbow_r',
 'seismic_r',
 'spring_r',
 'summer_r',
 'terrain_r',
 'winter_r',
 'Accent_r',
 'Dark2_r',
 'Paired_r',
 'Pastel1_r',
 'Pastel2_r',
 'Set1_r',
 'Set2_r',
 'Set3_r',
 'tab10_r',
 'tab20_r',
 'tab20b_r',
 'tab20c_r',
 'grey_r',
 'gist_grey_r',
 'gist_yerg_r',
 'Grays_r']

In [18]:
pivot2 = pd.pivot_table(df, index = ['Region', 'Type'], values = 'Sales', aggfunc = ['sum','count'])

In [19]:
pivot2

                              sum count
                            Sales Sales
Region Type
East   Children's Clothing  45849   113
       Men's Clothing       51685   122
       Women's Clothing     70229   176
North  Children's Clothing  37306    85
       Men's Clothing       39975    89
       Women's Clothing     61419   142
South  Children's Clothing  18570    45
       Men's Clothing       18542    39
       Women's Clothing     22203    53
West   Children's Clothing  20182    42
       Men's Clothing       19077    41
       Women's Clothing     22217    53

In [20]:
pivot2.style.background_gradient(cmap='Greens')

In [21]:
pivot2.style.background_gradient(subset=['sum'], cmap='Greens')

In [22]:
pivot.style.format({'Sales':'${0:,.0f}'}).bar(color='Green')

In [23]:
style1.style.format({'Sales':'${0:,.0f}'}).bar(color='Green')
style2.use(style1.export())

NameError: name 'style1' is not defined

# Pivot

In [27]:
df

          Date Region                 Type  Units  Sales
0   2020-07-11   East  Children's Clothing   18.0    306
1   2020-09-23  North  Children's Clothing   14.0    448
2   2020-04-02  South     Women's Clothing   17.0    425
3   2020-02-28   East  Children's Clothing   26.0    832
4   2020-03-19   West     Women's Clothing    3.0     33
..         ...    ...                  ...    ...    ...
995 2020-02-11   East  Children's Clothing   35.0    735
996 2020-12-25  North       Men's Clothing    NaN   1155
997 2020-08-31  South       Men's Clothing   13.0    208
998 2020-08-23  South     Women's Clothing   17.0    493
999 2020-08-17  North     Women's Clothing   25.0    300

[1000 rows x 5 columns]

In [29]:
pivot = pd.pivot_table(
    data=df,
    index='Region',
    values='Sales'
)
print(pivot)

             Sales
Region
East    408.182482
North   438.924051
South   432.956204
West    452.029412

In [33]:
pivot = pd.pivot_table(
    data=df,
    index='Region',
    values=['Sales','Units'],
    aggfunc='sum'
)
print(pivot)

         Sales   Units
Region
East    167763  8110.0
North   138700  4359.0
South    59315  2798.0
West     61476  2624.0

In [35]:
pivot = pd.pivot_table(
    data=df,
    index='Region',
    columns='Type',
    values='Sales'
)
print(pivot)

Type    Children's Clothing  Men's Clothing  Women's Clothing
Region
East             405.743363      423.647541        399.028409
North            438.894118      449.157303        432.528169
South            412.666667      475.435897        418.924528
West             480.523810      465.292683        419.188679

In [36]:
pivot = pd.pivot_table(
    data=df,
    index=['Region',df['Date'].dt.quarter],
    columns='Type',
    values='Sales'
)

print(pivot.head())

Type         Children's Clothing  Men's Clothing  Women's Clothing
Region Date
East   1              423.241379      369.250000        428.948718
       2              274.800000      445.425000        456.816327
       3              425.382353      506.421053        342.386364
       4              453.866667      405.666667        364.795455
North  1              394.727273      450.869565        489.944444

In [37]:
print(pivot.loc[('East', 1), "Men's Clothing"])

369.25

In [38]:
# Adding totals to rows and columns
pivot = pd.pivot_table(
    data=df,
    index='Region',
    columns='Type',
    values='Sales',
    margins=True
)
print(pivot)

Type    Children's Clothing  Men's Clothing  Women's Clothing         All
Region
East             405.743363      423.647541        399.028409  408.182482
North            438.894118      449.157303        432.528169  438.924051
South            412.666667      475.435897        418.924528  432.956204
West             480.523810      465.292683        419.188679  452.029412
All              427.743860      444.257732        415.254717  427.254000

In [39]:
# Adding totals to rows and columns
pivot = pd.pivot_table(
    data=df,
    index='Region',
    columns='Type',
    values='Sales',
    margins=True,
    margins_name='Total'
)
print(pivot)

Type    Children's Clothing  Men's Clothing  Women's Clothing       Total
Region
East             405.743363      423.647541        399.028409  408.182482
North            438.894118      449.157303        432.528169  438.924051
South            412.666667      475.435897        418.924528  432.956204
West             480.523810      465.292683        419.188679  452.029412
Total            427.743860      444.257732        415.254717  427.254000

In [40]:
pivot = pd.pivot_table(
    data=df,
    index='Region',
    values='Sales',
    sort=True
)

print(pivot)

             Sales
Region
East    408.182482
North   438.924051
South   432.956204
West    452.029412