In [33]:
!python --version

UnboundLocalError: cannot access local variable 'child' where it is not associated with a value

1245.77s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

In [ ]:
import pandas as pd

# Sample DataFrame
data = {
    'Department': ['IT', 'IT', 'HR', 'HR', 'Finance', 'Finance'],
    'Salary': [60000, 75000, 50000, 52000, 80000, 82000],
    'YearsExperience': [2, 3, 5, 4, 6, 7]
}

df = pd.DataFrame(data)

In [ ]:
df.groupby('Department')['Salary'].mean()

Department
Finance    81000.0
HR         51000.0
IT         67500.0
Name: Salary, dtype: float64

In [ ]:
# Custom multiple aggregation
df.groupby('Department').agg({
    'Salary': ['mean', 'sum'],
    'YearsExperience': 'max'
})

             Salary         YearsExperience
               mean     sum             max
Department
Finance     81000.0  162000               7
HR          51000.0  102000               5
IT          67500.0  135000               3

In [ ]:
df.groupby('Department').agg(
    lambda x: x.max() - x.min()
)

            Salary  YearsExperience
Department
Finance       2000                1
HR            2000                1
IT           15000                1

In [ ]:
df.groupby('Department')['Salary'].apply(lambda x: (x.max() + x.min()) / 2)

Department
Finance    81000.0
HR         51000.0
IT         67500.0
Name: Salary, dtype: float64

In [ ]:
df.groupby('Department').agg(
    avg_salary=('Salary', 'mean'),
    total_exp=('YearsExperience', 'sum')
)

            avg_salary  total_exp
Department
Finance        81000.0         13
HR             51000.0          9
IT             67500.0          5

In [ ]:
df.groupby('Department').agg(
    avg_salary=('Salary', 'mean'),
    total_exp=('YearsExperience', 'sum')).reset_index()

  Department  avg_salary  total_exp
0    Finance     81000.0         13
1         HR     51000.0          9
2         IT     67500.0          5

In [ ]:
df.groupby('Department')['Salary'].sum().reset_index()

  Department  Salary
0    Finance  162000
1         HR  102000
2         IT  135000

In [ ]:
df.describe()                     # Summary for entire DataFrame

             Salary  YearsExperience
count      6.000000         6.000000
mean   66500.000000         4.500000
std    14279.355728         1.870829
min    50000.000000         2.000000
25%    54000.000000         3.250000
50%    67500.000000         4.500000
75%    78750.000000         5.750000
max    82000.000000         7.000000

In [ ]:
df.groupby('Department').describe()  # Summary per group

           Salary                                                             \
            count     mean           std      min      25%      50%      75%
Department
Finance       2.0  81000.0   1414.213562  80000.0  80500.0  81000.0  81500.0
HR            2.0  51000.0   1414.213562  50000.0  50500.0  51000.0  51500.0
IT            2.0  67500.0  10606.601718  60000.0  63750.0  67500.0  71250.0

                    YearsExperience
                max           count mean       std  min   25%  50%   75%  max
Department
Finance     82000.0             2.0  6.5  0.707107  6.0  6.25  6.5  6.75  7.0
HR          52000.0             2.0  4.5  0.707107  4.0  4.25  4.5  4.75  5.0
IT          75000.0             2.0  2.5  0.707107  2.0  2.25  2.5  2.75  3.0

In [ ]:
df.groupby('Department').describe().reset_index()

  Department Salary                                                    \
              count     mean           std      min      25%      50%
0    Finance    2.0  81000.0   1414.213562  80000.0  80500.0  81000.0
1         HR    2.0  51000.0   1414.213562  50000.0  50500.0  51000.0
2         IT    2.0  67500.0  10606.601718  60000.0  63750.0  67500.0

                    YearsExperience
       75%      max           count mean       std  min   25%  50%   75%  max
0  81500.0  82000.0             2.0  6.5  0.707107  6.0  6.25  6.5  6.75  7.0
1  51500.0  52000.0             2.0  4.5  0.707107  4.0  4.25  4.5  4.75  5.0
2  71250.0  75000.0             2.0  2.5  0.707107  2.0  2.25  2.5  2.75  3.0

In [ ]:
# GroupBy is faster when the column is category type.
df['Department'] = df['Department'].astype('category')

In [ ]:
# Use sort=False in GroupBy
df.groupby('Department', sort=False).agg({...})

# Pre-filter Columns for Aggregation
df[['Department', 'Salary', 'YearsExperience']].groupby('Department').agg({...})

In [34]:
# Use Vectorized Aggregation Instead of Loops
# Slow
df.groupby('Department').apply(lambda x: x['Salary'].max() - x['Salary'].min())

/var/folders/f7/m8hfzm0j30l8vf635dzs58lc0000gn/T/ipykernel_5192/2040605907.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Department').apply(lambda x: x['Salary'].max() - x['Salary'].min())

Department
Finance     2000
HR          2000
IT         15000
dtype: int64

In [35]:
# Fast
df.groupby('Department')['Salary'].agg(lambda x: x.max() - x.min())

/var/folders/f7/m8hfzm0j30l8vf635dzs58lc0000gn/T/ipykernel_5192/3978118400.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Department')['Salary'].agg(lambda x: x.max() - x.min())

Department
Finance     2000
HR          2000
IT         15000
Name: Salary, dtype: int64

In [36]:
# Use Named Aggregation 
df.groupby('Department').agg(
    avg_salary=('Salary', 'mean'),
    max_exp=('YearsExperience', 'max')
)

/var/folders/f7/m8hfzm0j30l8vf635dzs58lc0000gn/T/ipykernel_5192/3233292459.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Department').agg(

            avg_salary  max_exp
Department
Finance        81000.0        7
HR             51000.0        5
IT             67500.0        3

In [37]:
# Defensive Aggregation 
safe_cols = ['Salary', 'YearsExperience']
available_cols = [col for col in safe_cols if col in df.columns]

df.groupby('Department')[available_cols].agg('mean')

/var/folders/f7/m8hfzm0j30l8vf635dzs58lc0000gn/T/ipykernel_5192/2214760956.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Department')[available_cols].agg('mean')

             Salary  YearsExperience
Department
Finance     81000.0              6.5
HR          51000.0              4.5
IT          67500.0              2.5

In [38]:
# ✅ 7. Drop NA Before Grouping If Needed
df = df.dropna(subset=['Department'])

In [41]:
# Use .values if only one column is needed after aggregation
grouped = df.groupby('Department')['Salary'].sum().values
grouped

/var/folders/f7/m8hfzm0j30l8vf635dzs58lc0000gn/T/ipykernel_5192/1826435089.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = df.groupby('Department')['Salary'].sum().values

array([162000, 102000, 135000])

In [48]:
# ✅ 9. Parallel Processing with Dask (for VERY large data)
import dask.dataframe as dd

ddf = dd.from_pandas(df, npartitions=4)
ddf.groupby('Department')['Salary'].mean().compute()

ImportError: pyarrow>=7.0.0 is required for PyArrow backed StringArray.

In [51]:
# !pip install dask
# !pip install pyarrow==7.0.0

In [52]:
import pandas as pd

df = pd.DataFrame({
    'date': ['2023-01-01', '2023-01-01', '2023-01-02'],
    'category': ['A', 'B', 'A'],
    'value': [10, 20, 30]
})

pivot = pd.pivot_table(df, index='date', columns='category', values='value', aggfunc='sum')
pivot = pivot.reset_index()

In [53]:
pivot

category        date     A     B
0         2023-01-01  10.0  20.0
1         2023-01-02  30.0   NaN

In [69]:
import pandas as pd

df = pd.DataFrame({
    'date': ['2023-01-01', '2023-01-01', '2023-01-02'],
    'category': ['A', 'B', 'A'],
    'value': [10, 20, 30]
})

pivot_df = pd.pivot_table(
    df,
    index='date',          # You want to group by date
    columns='category',    # You want categories to become columns
    values='value',
    aggfunc='sum',
    fill_value=0           # Optional: fill NaNs with 0
)

# Flatten multi-index columns (optional if you use multiple aggregations)
pivot_df.columns.name = None

# 🔑 Step: Reset index so 'date' becomes a column again
pivot_df = pivot_df.reset_index()

In [62]:
pivot_df.reset_index(drop=True)

         date   A   B
0  2023-01-01  10  20
1  2023-01-02  30   0

In [71]:
pivot_df.reset_index().set_index('date',inplace=True)

In [72]:
pivot_df

         date   A   B
0  2023-01-01  10  20
1  2023-01-02  30   0

In [73]:
pivot_df.columns

Index(['date', 'A', 'B'], dtype='object')

In [74]:
df3 = pivot_df[pivot_df.columns].copy()

In [79]:
df3.set_index('date',inplace=True)

KeyError: "None of ['date'] are in the columns"

In [80]:
df2 = pivot_df[['A', 'B']].copy()

In [81]:
df2.columns

Index(['A', 'B'], dtype='object')

In [82]:
df2.index

RangeIndex(start=0, stop=2, step=1)

In [83]:
df2

    A   B
0  10  20
1  30   0

In [84]:
import pandas as pd

# Sample df1
df1 = pd.DataFrame({
    'date': ['2023-01-01', '2023-01-02'],
    'col1': [10, 20],
    'col2': [30, 40],
    'col3': [99, 100]
})

# Select and set index
df2 = df1[['date', 'col1', 'col2']].copy()
df2['date'] = pd.to_datetime(df2['date'])  # ensure datetime type
df2.set_index('date', inplace=True)

print(df2)

            col1  col2
date
2023-01-01    10    30
2023-01-02    20    40